pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository using the correct credentials ID
                git credentialsId: 'github-credentials', url: 'https://github.com/eyaakhalij/bookstore-app.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                // Build the Docker image with an explicit path to the Dockerfile and build context
                // Fixing the path issue by quoting the path
                sh 'docker build -t bookstore-app:latest -f "Desktop/Book Store/Dockerfile" .'
            }
        }

        stage('Test') {
            steps {
                // Run tests (if applicable)
                sh './run_tests.sh'
            }
        }

        stage('Deploy') {
            steps {
                // Deploy the application using docker-compose
                sh 'docker-compose up -d'
            }
        }
    }
}
