pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/eyaakhalij/bookstore-app.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh 'docker-compose -f "C:/Users/Eya/Desktop/Book Store/docker-compose.yml" build'
            }
        }

        stage('Test') {
            steps {
                sh 'chmod +x C:/Users/Eya/Desktop/Book Store/run_tests.sh'
                sh 'C:/Users/Eya/Desktop/Book Store/run_tests.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose -f "C:/Users/Eya/Desktop/Book Store/docker-compose.yml" up -d'
            }
        }
    }
}
