pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                git credentialsId: 'your-credentials-id', url: 'https://github.com/eyaakhalij/bookstore-app.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                // Build the Docker image using docker-compose
                sh 'docker-compose build'
            }
        }

        stage('Test') {
            steps {
                // Run tests (if applicable)
                sh './run_tests.sh'
            }
        }

        stage('Deploy') {
            steps {
                // Deploy the application using docker-compose
                sh 'docker-compose up -d'
            }
        }
    }
}
